"use client";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";

import "@mantine/carousel/styles.css";
import "@mantine/dates/styles.css";
import {
  ColorSchemeScript,
  MantineColorsTuple,
  MantineProvider,
  createTheme,
} from "@mantine/core";

import { ThemeProvider } from "next-themes";

import Header from "@/layout/header";
import Footer from "@/layout/footer";
import ModalProvider from "@/providers/modal-provider";
import { FormspreeProvider } from "@formspree/react";
import Image from "next/image";
import classes from "@/app/button.module.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const myColor: MantineColorsTuple = [
  "#e7feed",
  "#d4fade",
  "#a9f2bd",
  "#7beb99",
  "#54e47a",
  "#3ce167",
  "#2edf5c",
  "#1ec54b",
  "#11af41",
  "#009834",
];

const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
});

const theme = createTheme({
  colors: {
    myColor,
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={poppins.className}>
        <ThemeProvider attribute="class" enableSystem enableColorScheme>
          <MantineProvider theme={theme}>
            <ModalProvider>
              {/* <main className="flex flex-col min-h-[100vh]">
                <Header />

                {children}
                <Footer />
              </main> */}
              {children}
            </ModalProvider>
          </MantineProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
